[package]
name = "rotp"
version = "0.1.0"
authors = ["V0id2Nu11"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
